import "dotenv/config";
import argon2 from "argon2";
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const name=process.env.ADMIN_NAME, email=process.env.ADMIN_EMAIL, password=process.env.ADMIN_PASSWORD;
  if(!name||!email||!password||password.length<12) throw new Error("ADMIN_NAME, ADMIN_EMAIL and ADMIN_PASSWORD (12+ chars) are required.");
  await prisma.admin.upsert({where:{email:email.toLowerCase()},update:{name,isActive:true,passwordHash:await argon2.hash(password)},create:{name,email:email.toLowerCase(),passwordHash:await argon2.hash(password),role:"ADMIN"}});
  const samples = [
    {title:"Web Development",slug:"web-development",tagline:"Web experiences built to convert and scale",category:"Software Development",shortDescription:"Strategy, UX, engineering, integrations and ongoing optimization for modern websites.",description:"# Web Development\n\nWe plan, design and engineer fast, accessible websites around measurable business outcomes.\n\n## What you receive\n\nA production-ready platform, analytics, documentation and a clear path for continuous improvement.",imageUrl:"https://images.unsplash.com/photo-1461749280684-dccba630e2f6",heroImageUrl:"https://images.unsplash.com/photo-1498050108023-c5249f4df085",features:["Responsive experience","Content management","Analytics and conversion tracking","Third-party integrations","Accessibility and SEO"],benefits:["Faster publishing","Higher conversion confidence","Maintainable architecture"],deliverables:["Discovery report","Information architecture","UI system","Production website","Handover documentation"],technologies:["TypeScript","React","Next.js","Node.js","PostgreSQL"],startingPrice:"Custom quote",estimatedTimeline:"6–14 weeks",process:[{step:1,title:"Discovery",description:"Goals, users, content and technical constraints.","duration":"1–2 weeks"},{step:2,title:"Design",description:"Information architecture, wireframes and interface design.","duration":"2–4 weeks"},{step:3,title:"Build and launch",description:"Engineering, QA, deployment and handover.","duration":"3–8 weeks"}],faqs:[{question:"Can you work with our existing brand?",answer:"Yes. We can extend an established design system or help create a new digital direction."}],order:0},
    {title:"Mobile App Development",slug:"mobile-app-development",tagline:"Useful mobile products people return to",category:"Software Development",shortDescription:"End-to-end iOS and Android product design and engineering.",description:"# Mobile App Development\n\nFrom validated concept through App Store and Play Store delivery.",features:["iOS and Android","Push notifications","Offline-first workflows","Payments and subscriptions","Store submission support"],benefits:["One product team","Shared cross-platform foundations","Release-ready quality"],deliverables:["Product roadmap","Interactive prototype","Mobile application","Backend APIs","Store release package"],technologies:["React Native","Flutter","Swift","Kotlin","Node.js"],startingPrice:"Custom quote",estimatedTimeline:"10–24 weeks",order:1},
    {title:"Cloud & DevOps",slug:"cloud-devops",tagline:"Infrastructure that stays reliable as you grow",category:"Cloud",shortDescription:"Cloud architecture, migrations, delivery automation, observability and operations.",description:"# Cloud & DevOps\n\nSecure, repeatable infrastructure designed around uptime, cost and team velocity.",features:["Cloud architecture","CI/CD","Infrastructure as code","Monitoring","Security hardening"],benefits:["Safer releases","Lower operational risk","Clear infrastructure ownership"],deliverables:["Architecture plan","Infrastructure code","Delivery pipelines","Runbooks"],technologies:["AWS","Azure","Docker","Terraform","Kubernetes"],startingPrice:"Custom quote",estimatedTimeline:"4–12 weeks",order:2},
    {title:"Data & AI",slug:"data-ai",tagline:"Turn operational data into useful decisions",category:"Data",shortDescription:"Analytics platforms, automation and responsible AI integrated into real workflows.",description:"# Data & AI\n\nWe build data foundations and focused AI tools with measurable operational value.",features:["Data pipelines","Dashboards","Workflow automation","AI assistants","Model integration"],benefits:["Faster decisions","Less repetitive work","Trusted reporting"],deliverables:["Data assessment","Solution architecture","Production implementation","Governance guide"],technologies:["Python","PostgreSQL","OpenAI","Power BI"],startingPrice:"Custom quote",estimatedTimeline:"6–16 weeks",order:3}
  ];
  const services=[]; for(const data of samples) services.push(await prisma.service.upsert({where:{slug:data.slug},update:data,create:data}));
  await prisma.project.upsert({where:{slug:"commerce-platform"},update:{kind:"WEB_APP"},create:{title:"Commerce Platform",slug:"commerce-platform",kind:"WEB_APP",summary:"A scalable retail experience connecting product discovery, checkout and fulfillment.",content:"# Commerce Platform\n\nA responsive commerce platform designed for reliable growth.",coverImageUrl:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d",galleryImages:["https://images.unsplash.com/photo-1556742049-0cfed4f6a45d"],screenshots:["https://images.unsplash.com/photo-1460925895917-afdab827c52f"],projectUrl:"https://example.com",status:"PUBLISHED",publishedAt:new Date(),order:0,isFeatured:true,technologies:["TypeScript","React","PostgreSQL"],platforms:["Web"],features:["Product discovery","Secure checkout","Operations dashboard"],results:[{label:"Performance",value:"90+ Lighthouse",description:"Optimized critical customer journeys."}],services:{create:[{serviceId:services[0].id},{serviceId:services[2].id}]}}});
  await prisma.project.upsert({where:{slug:"privion-mobile-demo"},update:{kind:"MOBILE_APP"},create:{title:"Privion Mobile Demo",slug:"privion-mobile-demo",kind:"MOBILE_APP",summary:"A reference mobile product demonstrating polished cross-platform delivery.",content:"# Privion Mobile Demo\n\nA representative app entry. Replace its URLs with the live store listings before production.",coverImageUrl:"https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",screenshots:["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c"],platforms:["iOS","Android"],features:["Secure onboarding","Real-time updates","Push notifications"],technologies:["React Native","Node.js"],status:"PUBLISHED",publishedAt:new Date(),order:1,isFeatured:true,services:{create:[{serviceId:services[1].id}]}}});
  await prisma.project.upsert({where:{slug:"analytics-workspace"},update:{},create:{title:"Analytics Workspace",slug:"analytics-workspace",summary:"An analytics project in progress.",content:"# Analytics Workspace",status:"DRAFT",order:1,technologies:["Python"],services:{create:[{serviceId:services[2].id}]}}});
  await prisma.siteSettings.upsert({where:{id:1},update:{contactEmail:"priviontech@gmail.com"},create:{id:1,companyName:"Privion Technologies",contactEmail:"priviontech@gmail.com",defaultSeoTitle:"Privion Technologies",defaultSeoDescription:"Technology services built around your business."}});
}
main().finally(()=>prisma.$disconnect());
